name: Build OpenWrt Release

on:
 # schedule:
 #   - cron: "0 2 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

env:
  VERSION: "17.01.6"
  BOARD: "ramips"
  SUBTARGET: "rt305x"
  PROFILE: "wr512-3gn-4M"
  PACKAGES_TYPE1: "luci luci-theme-material kmod-wireguard luci-app-wireguard wireguard-tools luci-proto-wireguard  -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -ppp -ppp-mod-pppoe"
  PACKAGES_TYPE2: "uhttpd uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-mod-admin-full luci-theme-material kmod-wireguard luci-app-wireguard wireguard-tools luci-proto-wireguard -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -ppp -ppp-mod-pppoe -opkg"    
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /mnt/workdir
        sudo chown $USER:$GROUPS /mnt/workdir
    - name: Download imagebuilder
      working-directory: /mnt/workdir
      run: |
        curl -O "https://archive.openwrt.org/releases/${{ env.VERSION }}/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/lede-imagebuilder-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64.tar.xz"
        tar xvaf lede-imagebuilder-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64.tar.xz
        ln -sf /mnt/workdir/lede-imagebuilder-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64 $GITHUB_WORKSPACE/lede
 
    # Pull the first six letters from the version.buildinfo-file for naming the release e. g. "R16767"
    - name: Download version info
      run: 
        echo "LEDE_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV 
     
    - name: Include External ipk-Packages
      run: |
        wget -O packages.txt https://github.com/minax007/packages/raw/main/external-package-urls.txt
        cat packages.txt | xargs wget -P /mnt/workdir/lede-imagebuilder-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64/packages
        
    - name: Build the image of type 1
      id: type1
      run: |
        cd lede
        make image PROFILE="${{ env.PROFILE }}" PACKAGES="${{ env.PACKAGES_TYPE1 }}"
        mv bin/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/lede-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}-${{ env.PROFILE }}-squashfs-sysupgrade.bin OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_sysupgrade.bin
    - name: Build the image of type 2
      id: type2
      run: |
        cd lede
        make image PROFILE="${{ env.PROFILE }}" PACKAGES="${{ env.PACKAGES_TYPE2 }}"
        mv bin/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/lede-${{ env.VERSION }}-${{ env.BOARD }}-${{ env.SUBTARGET }}-${{ env.PROFILE }}-squashfs-sysupgrade.bin OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_MINI_sysupgrade.bin


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}_release
        release_name: OpenWrt WR512-3GN-4M (${{ env.VERSION }}) release
        body: |
          This release is based on OpenWrt ${{ env.VERSION }}.
                    
        draft: false
        prerelease: false

    - name: Upload type1 Asset
      id: upload-release-asset-type1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: lede/OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_sysupgrade.bin
        asset_name: OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_sysupgrade.bin
        asset_content_type: application/bin

    - name: Upload type2 Asset
      id: upload-release-asset-type2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: lede/OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_MINI_sysupgrade.bin
        asset_name: OpenWrt_WR512-3GN-4M_${{ env.VERSION }}_MINI_sysupgrade.bin
        asset_content_type: application/bin
